
name: Check the source code
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install packages
        working-directory: ./laravel
        run: cd laravel && npm ci
      - name: Prettier
        working-directory: ./laravel
        run: npm run prettier
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change
          ref: ${{ github.head_ref }}